package com.theshan.codeai.ui

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.theshan.codeai.databinding.ActivityResultBinding

class ResultActivity : AppCompatActivity() {

    private lateinit var binding: ActivityResultBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityResultBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val code = intent.getStringExtra("CODE") ?: ""

        binding.tvCode.text = code

        binding.btnBack.setOnClickListener {
            finish()
        }

        binding.btnCopy.setOnClickListener {
            val clipboard = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            val clip = ClipData.newPlainText("Generated Code", code)
            clipboard.setPrimaryClip(clip)
            Toast.makeText(this, "✅ Code copied!", Toast.LENGTH_SHORT).show()
        }

        binding.btnShare.setOnClickListener {
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, code)
                putExtra(Intent.EXTRA_SUBJECT, "Code generated by CodeAI by Theshan")
            }
            startActivity(Intent.createChooser(shareIntent, "Share Code"))
        }
    }
}
